[discord]
bot_name = "Bot"
bot_token = "yourdiscordbottoken"
bridge_channel_id = 0
webhook_id = 0
default_avatar = "examplelink.to/urimage"
color = "#8888ff"

[discord.permissions]
member_role = 0
admin_role = 0

[[servers]]
name = "example"
ip = "127.0.0.1"
port = 90000
ws_password = "badpassword"

[servers.chatbridge]
username = "Example"
nickname = "example server!"
color = "#ff0000"

[[servers]]
name = "example2"
ip = "127.0.0.1"
port = 90001
ws_password = "worse"

[servers.chatbridge]
username = "Example 2"
nickname = "other example server!"
color = "#00ff00"
